version: '3.1'

services:

  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: gpt3
      MONGO_INITDB_ROOT_PASSWORD: gpt3
    ports:
      - "27017:27017"

  bot:
    environment:
      DISCORD_TOKEN: MTA0OTA1ODk3ODI1NDA0MTE0OQ.G-lblD.lR5YIjk9PgTcXYNFk1f_T-F31T5QBL1Wt_mvR4
      MONGO_DBUSER: gpt3
      MONGO_DBPASS: gpt3
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DBNAME: gpt3
      PREFIX: !
      LOG_LEVEL: DEBUG
docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
